### ISSUE TITLE
bug: unable to install new @capgo/capacitor-data-storage-sqlite on iOS

### ISSUE THREAD

**Issue by mburger81** [Cap-go/capacitor-data-storage-sqlite#79] opened 2024-08-16 15:12 UTC
Hey @riderx in reference about the issue yesterday https://github.com/Cap-go/capacitor-data-storage-sqlite/issues/74#issuecomment-2290750555 unfortunately the issue is not resolved.

Using @6.0.4 I get still the same issue
`[!] No podspec found for 'CapgoCapacitorDataStorageSqlite'` in `../../node_modules/@capgo/capacitor-data-storage-sqlite`

But now instead of a wrong podspec file there is no file at all, look

```
ls -la node_modules/@capgo/capacitor-data-storage-sqlite
total 40
drwxr-xr-x  9 abc  staff   288 Aug 16 16:52 .
drwxr-xr-x  3 abc  staff    96 Aug 16 16:52 ..
-rw-r--r--  1 abc  staff  1086 Aug 16 16:52 LICENSE
drwxr-xr-x  4 abc  staff   128 Aug 16 16:52 android
drwxr-xr-x  8 abc  staff   256 Aug 16 16:52 dist
drwxr-xr-x  5 abc  staff   160 Aug 16 16:52 electron
drwxr-xr-x  3 abc  staff    96 Aug 16 16:52 ios
-rw-r--r--  1 abc  staff  3308 Aug 16 16:52 package.json
-rw-r--r--  1 abc  staff  9607 Aug 16 16:52 readme.md
```

**Comment by riderx** [comment] 2024-08-20 08:30
Can you try again ?
And sorry i don't know why i didn't received notif here

**Comment by WcaleNieWolny** [comment] 2024-09-11 04:35
Closing, cannot reproduce. Please try the latest version

**Closed by WcaleNieWolny** 2024-09-11 04:35 UTC
